# Generated by Django 6.0 on 2025-12-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.IntegerField(default=0),
        ),
    ]
