# Generated by Django 5.2.10 on 2026-03-25 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_paymentaccount_withdrawalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWalletConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_delay_days', models.IntegerField(default=7)),
                ('min_withdrawal', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('max_withdrawal', models.DecimalField(blank=True, decimal_places=2, default=10000.0, max_digits=10, null=True)),
                ('allow_unlimited_withdrawals', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EarningTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Release'), ('released', 'Released to Withdrawable'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_earnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.paymentaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('withdrawable_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_frozen', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
