# Generated by Django 5.2.10 on 2026-04-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_adminwalletconfig_earningtransaction_payoutlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN_LIMITED', 'Limited Admin'), ('ADMIN_MAIN', 'Main Admin'), ('MASTER_ADMIN', 'Master Admin')], default='USER', max_length=20),
        ),
    ]
