# Generated by Django 5.2.10 on 2026-01-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('GROUP', 'Group'), ('GLOBAL', 'Global'), ('LIVE', 'Live Stream')], max_length=10),
        ),
    ]
