# Generated by Django 5.2.10 on 2026-01-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_conversation_created_by_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('GROUP', 'Group'), ('GLOBAL', 'Global'), ('LIVE', 'Live Stream')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('SYSTEM', 'System'), ('GIFT', 'Gift')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='messagereceipt',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'Delivered'), ('READ', 'Read')], db_index=True, max_length=10),
        ),
    ]
