# Generated by Django 5.2.10 on 2026-01-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallbackVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('weight', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
