# Generated by Django 5.2.10 on 2026-02-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_alter_livestream_streamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='replay_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
