# Generated by Django 5.2.10 on 2026-02-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_livestream_replay_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestream',
            name='replay_url',
        ),
    ]
