# Generated by Django 5.2.10 on 2026-02-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_remove_livestream_replay_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='recorded_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
