# Generated by Django 5.2.10 on 2026-02-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_livestream_recorded_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestream',
            name='recorded_video_url',
        ),
    ]
