# Generated by Django 5.2.10 on 2026-02-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0007_remove_livestream_recorded_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
