# Generated by Django 5.2.11 on 2026-02-24 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0008_livestream_last_heartbeat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livestream',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='share_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CoHostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ended', 'Ended')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohost_requests', to='streaming.livestream')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohost_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('stream', 'viewer', 'status')},
            },
        ),
    ]
