# Generated by Django 5.2.10 on 2026-04-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0009_livestream_is_private_livestream_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='allow_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='allow_multiguest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livestream',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='stream_thumbnails/'),
        ),
        migrations.AddField(
            model_name='livestream',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
