# Generated by Django 5.2.10 on 2026-03-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_hours', models.IntegerField(choices=[(6, '6 Hours'), (12, '12 Hours'), (24, '24 Hours'), (48, '48 Hours')], unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_percentage', models.IntegerField(default=0, help_text='0-100')),
            ],
        ),
    ]
