# Generated by Django 5.2.10 on 2026-03-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_site', '0002_timesubscriptiontier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_amount', models.IntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_coins', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('coin_cost', models.IntegerField()),
                ('image_url', models.URLField(blank=True, help_text='URL to gift animation/image', null=True)),
                ('css_icon_class', models.CharField(blank=True, help_text='e.g. bx-gift', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'coin_cost'],
            },
        ),
    ]
