# Generated by Django 5.2.10 on 2026-03-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_site', '0003_coinpackage_virtualgift'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinpackage',
            name='name',
            field=models.CharField(default='Coin Pack', max_length=100),
        ),
        migrations.AddField(
            model_name='timesubscriptiontier',
            name='benefits',
            field=models.TextField(blank=True, help_text='Comma separated list of features'),
        ),
        migrations.AddField(
            model_name='timesubscriptiontier',
            name='name',
            field=models.CharField(default='Premium Plan', max_length=100),
        ),
        migrations.AlterField(
            model_name='coinpackage',
            name='coin_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timesubscriptiontier',
            name='duration_hours',
            field=models.IntegerField(help_text='Duration in hours (e.g. 6, 12, 48, 96, etc.)'),
        ),
    ]
