# Generated by Django 5.2.10 on 2026-01-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_coinledger_coinwallet_minuteledger_minutewallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuteledger',
            name='stripe_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='minuteledger',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='streamearning',
            name='payout_amount',
            field=models.BigIntegerField(),
        ),
    ]
