# Generated by Django 5.2.11 on 2026-02-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_minuteledger_stripe_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_amount', models.IntegerField(help_text='Amount of coins users receive', unique=True)),
                ('price_usd', models.DecimalField(decimal_places=2, help_text='Cost in USD', max_digits=8)),
                ('price_ngn', models.DecimalField(blank=True, decimal_places=2, help_text='Cost in Naira (Optional)', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['coin_amount'],
            },
        ),
    ]
